language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk: openjdk6
script:
  mvn verify
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
